name: "One-Click AWS Infra Manager"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - plan
          - destroy
      aws_region:
        description: "Target AWS Region"
        required: true
        default: "us-east-1"
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform ${{ github.event.inputs.action }}"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
         audience: sts.amazonaws.com
         aws-region: ${{ github.event.inputs.aws_region }}
         role-to-assume: ${{ vars.AWS_ROLE_ARN || 'arn:aws:iam::650694421089:role/github-actions-infra-deployer' }}
         role-session-name: GHA-Alamgir-${{ github.run_id }}

      - name: Verify STS Caller Identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        working-directory: ./terraform
        run: terraform plan -var="aws_region=${{ github.event.inputs.aws_region }}"

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        working-directory: ./terraform
        run: |
          terraform apply -var="aws_region=${{ github.event.inputs.aws_region }}" -auto-approve
          echo "### Infrastructure Deployed Successfully! 🚀" >> $GITHUB_STEP_SUMMARY
          echo "Public URL: $(terraform output -raw web_public_url)" >> $GITHUB_STEP_SUMMARY

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        working-directory: ./terraform
        run: terraform destroy -var="aws_region=${{ github.event.inputs.aws_region }}" -auto-approve
